version: '3.1'
services:
  quant-fe:
    container_name: quant-fe
    image: nginx
    restart: always
    ports:
      - 4009:80
    volumes:
      - ./quant-fe/nginx.conf:/etc/nginx/nginx.conf
      - ./quant-fe/mime.types:/etc/nginx/mime.types
      - ./quant-fe/static:/static
